import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import { AuthContextProvider } from "@/app/context/user-context";
import { Lato, Mukta } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["400"],
});

const mukta = Mukta({
  subsets: ["latin"],
  variable: "--font-mukta",
  weight: ["300"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" className={`${lato.variable} ${mukta.variable}`}>
        <body
          style={{
            margin: 0,
            padding: 0,
            minHeight: "100vh",
          }}
        >
          <AuthContextProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthContextProvider>
        </body>
      </html>
    </>
  );
}
