import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import { AuthContextProvider } from "@/app/store/user-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body
          style={{
            margin: 0,
            padding: 0,
          }}
        >
          <AuthContextProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthContextProvider>
        </body>
      </html>
    </>
  );
}
